
---

### 📄 `.github/workflows/deploy.yml`

```yaml
name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic tests
        run: |
          echo "Running tests..."
          python -m unittest discover tests

      - name: (Optional) Deploy step
        run: echo "Add deployment commands or integrate Render/Heroku"
